#!/bin/bash
if ! [ -z "$1" ]; then
    echo "usage:"
    echo "logout"
    exit 5
fi

if [ "$UID" == "0" ]; then
    echo "this script must be run as a regular user"
    exit 7
fi

qdbus6 org.kde.Shutdown /Shutdown org.kde.Shutdown.logout

# loginctl terminate-user would not properly return to SDDM. Using ghbus instead
