#!/bin/bash
if ! [ -z "$1" ]; then
    echo "usage:"
    echo "remove-first-setup-user"
    exit 5
fi

if ! [ "$UID" == "0" ]; then
    echo "this script must be run with super user privileges"
    exit 6
fi

usermod -s /usr/sbin/nologin $(id -nu $PKEXEC_UID || echo invaliduser)
cp /usr/share/org.vanillaos.FirstSetup/remove-first-setup-user.service /etc/systemd/system/remove-first-setup-user.service
systemctl enable remove-first-setup-user.service
