#!/bin/bash
if ! [ -z "$1" ]; then
    echo "usage:"
    echo "remove-panels"
    exit 5
fi

if [ "$UID" == "0" ]; then
    echo "this script must be run as a regular user"
    exit 7
fi

qdbus6 org.kde.plasmashell /PlasmaShell org.kde.PlasmaShell.evaluateScript "var panels = panels(); for (var i in panels) { panels[i].remove(); }"
