#!/bin/bash
if [ "$UID" == "0" ]; then
    echo "this script must be run as a regular user"
    exit 7
fi

if [ "$1" == "dark" ]; then

    lookandfeeltool -a org.kde.breezedark.desktop

elif [ "$1" == "light" ]; then

    lookandfeeltool -a org.kde.breeze.desktop

else
    echo "usage:"
    echo "theme <dark|light>"
    exit 5
fi
